### ISSUE TITLE
int(pd.NaT) not working in python3.9

### ISSUE THREAD

**Issue by UlyssesHung** [AlpacaDB/trading_calendars#26]
https://github.com/AlpacaDB/trading_calendars/blob/94e4a08c4fd6fbdd5f042a2a15cd9f7bc47b3941/trading_calendars/calendar_helpers.py#L5

Here is the error message
`TypeError: int() argument must be a string, a bytes-like object or a number, not 'NaTType'`

Environment:
- Docker image: `continuumio/miniconda3:4.10.3`
- `Python 3.9.5`
- `numpy==1.21.2`
- `pandas==1.3.3`

**Comment by sercant** [comment]
@UlyssesHung thanks for reporting this! Let's support these versions too. I will handle it or also if you are interested, feel free to make a PR 🙏

**Comment by UlyssesHung** [comment]
@sercant I discover the problem. I follow the readme page to install with `pip install trading-calendars` but it is using the old package `2.1.1` which not includes your fix in `2.1.1.1`. I check the requirement in `search` repo and install with `pip install git+https://github.com/alpacadb/trading_calendars.git@2.1.1.1` then it works fine.
